baseURL = 'https://awesome-javascript.netlify.app/'
languageCode = 'en-us'
title = 'Awesome Javascript'
theme = 'beautifulhugo'
summaryLength = 25
copyright = "Harendra Kumar Kanojiya"
# disqusShortname = "awesome-javascript"
#googleAnalytics = "UA-1XXXXXXX1-X"
pygmentsCodeFences = true
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
enableRobotsTXT = true
paginate = 10

[taxonomies]
  series = "series"
  tags = "tags"
[Params]
  homeTitle = 'Awesome Javascript'
  description = "Unlock the power of web development with our in-depth tutorials on JavaScript, React, and Angular. Explore hands-on examples and master the art of building dynamic and modern web applications."
  title = 'Awesome Javascript'
  subtitle = "Learn Javascript With Examples"
  mainSections = ["blog"]
  #logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = true
  rss = true
  comments = true
  readingTime = true
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = false
  showRelatedPosts = true
  hideAuthor = true
  gcse = "667de25a4f13c494d" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."
  timeZone = "Asia/Kolkata"
  generateTOC = true

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Harendra Kumar"
  website = "https://harendra21.github.io"
  email = "harendraverma21@gmail.com"
  facebook = "harendraverma21"
  github = "harendra21"
  #gitlab = "username"
  #bitbucket = "username"
  twitter = "harendraverma2"
  #reddit = "username"
  linkedin = "harendra21/"
  #xing = "username"
  stackoverflow = "users/6720451/harendra-kumar"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #elegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #eibo = "username"
  #slack = "username"
  #medium = "username"
  #discord = "invite code (https://discord.gg/XXXXXXX)"
  #strava = "userid"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
  name = "Sites"
  weight = 2
  identifier = "sites"

[[menu.main]]
  parent = "sites"
  name = "Awesome Golang"
  url = "https://awesome-golang.netlify.app/"
  weight = 1

[[menu.main]]
  parent = "sites"
  name = "Awesome Javascript"
  url = "https://awesome-javascript.netlify.app/"
  weight = 2

[[menu.main]]
    name = "About"
    url = "https://harendra21.github.io/"
    weight = 3
[[menu.main]]
    name = "Sitemap"
    url = "sitemap.xml"
    weight = 4
[[menu.main]]
    name = "Feeds"
    url = "index.xml"
    weight = 5