name: Push File

on: 
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'content/blog'
        destination_repo: 'harendra21/with-code-example'
        destination_folder: 'content/posts/javascript'
        user_email: 'harendraverma21@gmail.com'
        user_name: 'harendra21'
        commit_msg: '[GHA] Update the test files.'
